backend:
  name: git-gateway
  repo: Crosby-Solutions/wbc-tb-fixtures
  branch: master

media_folder: "static/media/uploads"
site_url: https://wbc-tb-fixtures.netlify.app

collections:
  - name: "divisions"
    label: "Divisions"
    folder: "content/_divisions/"
    create: true
    identifier_field: division
    filter: { field: "sport", value: "Teeball" }
    fields:
      - { label: "Division", name: "division", widget: "string" }
      - {
          label: "Sport",
          name: "sport",
          widget: "select",
          options: ["Teeball", "Little League", "Intermediate League"],
          default: "Teeball"
        }
      - {
          label: "Age",
          name: "age",
          widget: "select",
          options: ["8", "9", "10", "11", "12"]
        }
  - name: "clubs"
    label: "Clubs"
    folder: "content/_clubs/"
    create: true
    identifier_field: club
    fields:
      - { label: "Club Short", name: "club", widget: "string" }
      - { label: "Club Full", name: "club_full", widget: "string" }
      - {
          label: "Sport",
          name: "sport",
          widget: "select",
          options: ["Teeball", "Little League", "Intermediate League"],
          default: "Teeball"
        }
      - { label: "Logo", name: "logo", widget: "image" }
      - { label: "Website", name: "website", widget: "string" }
      - { label: "Primary Color", name: "color1", widget: "color" }
      - { label: "Secondary Color", name: "color2", widget: "color" }
      - { label: "Tertiary Color", name: "color3", widget: "color" }
      - { label: "Venue", name: "venue", widget: "map" }
  - name: "teams"
    label: "Teams"
    folder: "content/_teams/"
    create: true
    slug: "{{division}}-{{division_number}}{{club}}-{{slug}}"
    identifier_field: team
    display_fields: ["division", "division_number", "club", "team"]
    filter: { field: "sport", value: "Teeball" }
    sortable_fields: ["division", "division_number"]
    fields:
      - { label: "Team", name: "team", widget: "string" }
      - {
          label: "Club",
          name: "club",
          widget: "relation",
          collection: "clubs",
          search_fields: ["club"],
          value_field: "club",
          display_fields: ["club"]
        }
      - {
          label: "Sport",
          name: "sport",
          widget: "select",
          options: ["Teeball", "Little League", "Intermediate League"],
          default: "Teeball"
        }
      - {
          label: "Division",
          name: "division",
          widget: "relation",
          collection: "divisions",
          search_fields: ["division", "age"],
          value_field: "division",
          display_fields: ["division"]
        }
      - { label: "Division Number", name: "division_number", widget: "string" }
      - { label: "Logo", name: "logo", widget: "image", required: false }
      - {
          label: "Primary Color",
          name: "color1",
          widget: "color",
          required: false
        }
      - {
          label: "Secondary Color",
          name: "color2",
          widget: "color",
          required: false
        }
      - {
          label: "Tertiary Color",
          name: "color3",
          widget: "color",
          required: false
        }
      - {
          label: "Manager Name",
          name: "managerName",
          widget: "string",
          required: false
        }
  - name: "rounds"
    label: "Rounds"
    folder: "content/_rounds/"
    create: true
    identifier_field: round
    fields:
      - { label: "Round", name: "round", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - {
          label: "Division",
          name: "division",
          widget: "relation",
          collection: "divisions",
          search_fields: ["division", "age"],
          value_field: "division",
          display_fields: ["division"]
        }
  - name: "games"
    label: "Games"
    folder: "content/_games/"
    create: true
    identifier_field: game
    fields:
      - {
          label: "Round",
          name: "round",
          widget: "relation",
          collection: "rounds",
          search_fields: ["round", "date"],
          value_field: "round",
          display_fields: ["round"]
        }
      - { label: "Day", name: "day", widget: "string", default: "Saturday" }
      - { label: "Time", name: "time", widget: "string", default: "8.30am" }
      - {
          label: "Home Team",
          name: "teamHome",
          widget: "relation",
          collection: "teams",
          search_fields: ["team", "club"],
          value_field: "team",
          display_fields: ["club", "team"]
        }
      - {
          label: "Away Team",
          name: "teamAway",
          widget: "relation",
          collection: "teams",
          search_fields: ["team", "club"],
          value_field: "team",
          display_fields: ["club", "team"]
        }
      - { label: "Diamond", name: "diamond", widget: "number" }
